config/routes.rb
TravelAppCf::Application.routes.draw do

  devise_for :users

  root :to => "destinations#index"

  resources :destinations do
    resources :itineraries
  end

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :city, :country, :enddate, :startdate

  has_many :itineraries, :dependent => :destroy
  has_many :itineraries, :dependent => :delete_all
  has_many :itineraries, :dependent => :nullify

  validates :city, :presence => true
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :destination
  attr_accessible :activity, :city, :plandate

  validates :activity, :presence => true
  validates :city, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def index
    @destinations = Destination.all
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(params[:destination])
    if @destination.save
      flash[:notice] = "Destination has been created."
      redirect_to @destination
    else
      flash[:alert] = "Destination has not been created."
      render :action => "new"
    end
  end

  def show
    @destination = Destination.find(params[:id])
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update_attributes(params[:destination])
      flash[:notice] = "Destination has been updated."
      redirect_to @destination
    else
      flash[:alert] = "Destination has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    flash[:notice] = "Destination has been deleted."
    redirect_to destinations_path
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  before_filter :find_destination
  before_filter :find_itinerary, :only => [:show, :edit, :update, :destroy]

  def new
    @itinerary = @destination.itineraries.build
  end

  def create
    @itinerary = @destination.itineraries.build(params[:itinerary])
    if @itinerary.save
      flash[:notice] = "Itinerary has been created."
      redirect_to [@destination, @itinerary]
    else
      flash[:alert] = "Itinerary has not been created."
      render :action => "new"
    end
  end

  def show

  end

  def edit

  end

  def update
    if @itinerary.update_attributes(params[:itinerary])
      flash[:notice] = "Itinerary has been updated."
      redirect_to [@destination, @itinerary]
    else
      flash[:alert] = "Itinerary has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @itinerary.destroy
    flash[:notice] = "Itinerary has been deleted."
    redirect_to @destination
  end


  private
    def find_destination
      @destination = Destination.find(params[:destination_id])
    end

    def find_itinerary
      @itinerary = @destination.itineraries.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "TravelAppCf").join(" - ")
      end
    end
  end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <%= f.error_messages %>
    <p>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </p>

    <p>
      <%= f.label :country %>
      <%= f.text_field :country %>
    </p>

    <p>
      <%= f.label :startdate %>
      <%= f.datetime_select :startdate %>
    </p>

    <p>
      <%= f.label :enddate %>
      <%= f.datetime_select :enddate %>
    </p>

  <%= f.submit %>
<% end %>

app/views/destinations/edit.html.erb
<h2>Edit Destination</h2>
<%= render "form" %>

app/views/destinations/index.html.erb
<%= link_to "New Destination", new_destination_path %>

<h2>Destinations</h2>

<table>
  <tr>
    <th>City</th>
    <th>Country</th>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>

  <% @destinations.each do |destination| %>
    <tr>
      <td><%= link_to destination.city, destination %></td>
      <td><%= destination.country %></td>
      <td><%= destination.startdate %></td>
      <td><%= destination.enddate %></td>
    </tr>
  <% end %>
</table>

app/views/destinations/new.html.erb
<h2>New Destination</h2>

<%= render "form" %>

app/views/destinations/show.html.erb
<% title(@destination.city, "Destinations") %>

<h2><%= @destination.city %></h2>

<p>
  <%= link_to "Edit Destination", edit_destination_path(@destination) %>
  <%= link_to "Delete Destination", destination_path(@destination), :method => :delete, :confirm => "Are you sure you want to delete this destination?" %>
  <%= link_to "New Itinerary", new_destination_itinerary_path(@destination) %>
</p>

<ul id='destinations'>
  <% @destination.itineraries.each do |itinerary| %>
    <li>
      #<%= itinerary.id %> - <%= link_to itinerary.activity, [@destination, itinerary] %>
    </li>
  <% end %>
</ul>

app/views/itineraries/_form.html.erb
<%= form_for [@destination, @itinerary] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </p>

  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :plandate %>
    <%= f.datetime_select :plandate %>
  </p>

  <%= f.submit %>

<% end %>

app/views/itineraries/edit.html.erb
<h2>Editing an itinerary in <%= @destination.city %></h2>
<%= render "form" %>

app/views/itineraries/new.html.erb
<h2>New Itinerary</h2>

<%= render "form" %>

app/views/itineraries/show.html.erb
<div id='itinerary'>
  <h2><%= @itinerary.activity %></h2>
  <%= simple_format(@itinerary.city) %>
</div>

<%= link_to "Edit Itinerary", [:edit, @destination, @itinerary] %>
<%= link_to "Delete Itinerary", [@destination, @itinerary], :method => :delete, :confirm => "Are you sure you want to delete this itinerary?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      TravelAppCf
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  </nav>

  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
  <% end %>

  <%= yield %>

  <p>
    <%= link_to "Home", root_path %>
  </p>

</body>
</html>